# Generated by Django 4.1.3 on 2022-11-15 09:44

from django.db import migrations, models
import football_news_app.core.validators


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='personal_photo',
            field=models.ImageField(blank=True, upload_to='players_photos/', validators=[football_news_app.core.validators.validate_file_less_than_7mb]),
        ),
    ]
