# Generated by Django 4.1.3 on 2022-11-24 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0002_alter_player_personal_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='assists',
            field=models.PositiveIntegerField(default='0'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='player',
            name='goals',
            field=models.PositiveIntegerField(default='0'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='player',
            name='matches',
            field=models.PositiveIntegerField(default='0'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='player',
            name='rating',
            field=models.PositiveIntegerField(default='1'),
            preserve_default=False,
        ),
    ]
