# Generated by Django 4.1.3 on 2022-11-24 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0003_player_assists_player_goals_player_matches_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='team_number',
            field=models.PositiveIntegerField(default='0'),
            preserve_default=False,
        ),
    ]
