# Generated by Django 4.1.3 on 2022-11-17 10:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0002_message'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='articlelike',
            name='article',
        ),
        migrations.RemoveField(
            model_name='articlelike',
            name='user',
        ),
        migrations.DeleteModel(
            name='ArticleComment',
        ),
        migrations.DeleteModel(
            name='ArticleLike',
        ),
    ]
