# Generated by Django 4.1.3 on 2022-11-14 11:00

from django.db import migrations, models
import football_news_app.core.model_mixins


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team_name', models.CharField(max_length=30)),
                ('team_logo_photo', models.URLField()),
                ('slug', models.SlugField(blank=True, unique=True)),
            ],
            bases=(football_news_app.core.model_mixins.StrFromFieldsMixin, models.Model),
        ),
    ]
