# Generated by Django 4.1.3 on 2022-11-24 14:51

from django.db import migrations, models
import football_news_app.core.validators


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='team_logo_photo',
            field=models.ImageField(blank=True, upload_to='teams_logos/', validators=[football_news_app.core.validators.validate_file_less_than_7mb]),
        ),
    ]
