# Generated by Django 4.1.3 on 2022-11-24 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0002_alter_team_team_logo_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='team_logo_photo',
            field=models.URLField(),
        ),
    ]
