# Generated by Django 4.1.3 on 2022-11-24 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0003_alter_team_team_logo_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='stadium',
            field=models.CharField(default='1', max_length=40),
            preserve_default=False,
        ),
    ]
