# Generated by Django 4.1.3 on 2022-11-14 11:01

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import football_news_app.core.validators
import football_news_app.core.model_mixins


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('teams', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(max_length=40)),
                ('photo', models.ImageField(blank=True, upload_to='articles_photos/', validators=[football_news_app.core.validators.validate_file_less_than_7mb])),
                ('description', models.CharField(blank=True, max_length=500, null=True, validators=[django.core.validators.MinLengthValidator(10)])),
                ('publication_date', models.DateField(auto_now=True)),
                ('tagged_teams', models.ManyToManyField(blank=True, to='teams.team')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to=settings.AUTH_USER_MODEL)),
            ],
            bases=(football_news_app.core.model_mixins.StrFromFieldsMixin, models.Model),
        ),
    ]
