# Generated by Django 4.1.3 on 2022-11-14 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='title',
            field=models.CharField(default='1', max_length=40),
            preserve_default=False,
        ),
    ]
