# Generated by Django 4.1.3 on 2022-11-14 14:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0004_remove_article_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='tagged_teams',
        ),
    ]
