# Generated by Django 4.1.3 on 2022-12-13 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0007_articlelike_articlecomment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='title',
            field=models.CharField(max_length=100),
        ),
    ]
