# Generated by Django 4.1.3 on 2022-12-05 08:01

from django.db import migrations, models
import football_news_app.core.validators


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_appuser_profile_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appuser',
            name='profile_photo',
            field=models.ImageField(blank=True, default='1', upload_to='profile_photos/', validators=[football_news_app.core.validators.validate_file_less_than_7mb]),
            preserve_default=False,
        ),
    ]
