# Generated by Django 4.1.3 on 2022-12-09 15:26

import django.core.validators
from django.db import migrations, models
import football_news_app.core.validators


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_alter_appuser_profile_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appuser',
            name='first_name',
            field=models.CharField(max_length=30, validators=[django.core.validators.MinLengthValidator(2), football_news_app.core.validators.validate_only_letters], verbose_name='First Name'),
        ),
    ]
