# Generated by Django 4.1.3 on 2022-11-14 11:01

import django.core.validators
from django.db import migrations, models
import football_news_app.core.validators
import football_news_app.core.model_mixins


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('home_team', models.CharField(max_length=40)),
                ('guest_team', models.CharField(max_length=40)),
                ('photo', models.ImageField(blank=True, upload_to='matches-photos/', validators=[football_news_app.core.validators.validate_file_less_than_7mb])),
                ('league', models.CharField(blank=True, max_length=30, null=True, validators=[django.core.validators.MinLengthValidator(2)])),
                ('match_date', models.DateField(blank=True)),
                ('match_location', models.CharField(blank=True, max_length=30, null=True, validators=[django.core.validators.MinLengthValidator(2)])),
            ],
            bases=(football_news_app.core.model_mixins.StrFromFieldsMixin, models.Model),
        ),
    ]
