# Generated by Django 4.1.3 on 2022-11-24 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0002_match_price_match_ticket_numbers_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='match',
            name='price',
        ),
        migrations.RemoveField(
            model_name='match',
            name='ticket_numbers',
        ),
        migrations.AddField(
            model_name='match',
            name='league_stage',
            field=models.CharField(default='1', max_length=30),
            preserve_default=False,
        ),
    ]
